FROM node:20-slim AS builder
WORKDIR /app
COPY . .
RUN npm install -g pnpm
RUN pnpm install
RUN pnpm --filter api build

FROM node:20-slim
WORKDIR /app
COPY --from=builder /app/package.json .
COPY --from=builder /app/pnpm-workspace.yaml .
COPY --from=builder /app/apps/api ./apps/api
COPY --from=builder /app/node_modules ./node_modules
RUN npm install -g pnpm
EXPOSE 3001
CMD ["pnpm", "--filter", "api", "start"]
